class Story {
    constructor(story) {
      this.id = story.id,               // story id
      this.photo = story.photo,          // story photo (or user photo)
      this.name = story.name,             // story name (or user name)
      this.link = story.link,             // story link (useless on story generated by script)
      this.lastUpdated = story.lastUpdated,      // last updated date in unix time format
      this.seen = false,          // set true if user has opened

      this.items = story.items
    //   [              // array of items
    //       // story item example
    //       {
    //         id: "",       // item id
    //         type: "",     // photo or video
    //         length: 3,    // photo timeout or video length in seconds - uses 3 seconds timeout for images if not set
    //         src: "",      // photo or video src
    //         preview: "",  // optional - item thumbnail to show in the story carousel instead of the story defined image
    //         link: "",     // a link to click on story
    //         linkText: "", // link text
    //         time: "",     // optional a date to display with the story item. unix timestamp are converted to "time ago" format
    //         seen: false   // set true if current user was read,
            
    //       }
    //     ]
      
    }

    // methods will be written below

  }


// example of a story
let Stories = new Story({
    id: 1,
    photo : "#",          // story photo (or user photo)
    name : "fotiecodes",             // story name (or user name)
    link : "#",             // story link (useless on story generated by script)
    lastUpdated : "2004-09-16T00:00:00Z",      // last updated date in unix time format
    seen : false,          // set true if user has opened
    items : [
        {
            id: 1,       // item id
            type: "photo",     // photo or video
            length: 3,    // photo timeout or video length in seconds - uses 3 seconds timeout for images if not set
            src: "",      // photo or video src
            preview: "",  // optional - item thumbnail to show in the story carousel instead of the story defined image
            link: "",     // a link to click on story
            linkText: "", // link text
            time: "",     // optional a date to display with the story item. unix timestamp are converted to "time ago" format
            seen: false   // set true if current user was read,
            
          },
          {
            id: 1,       // item id
            type: "video",     // photo or video
            length: 3,    // photo timeout or video length in seconds - uses 3 seconds timeout for images if not set
            src: "",      // photo or video src
            preview: "",  // optional - item thumbnail to show in the story carousel instead of the story defined image
            link: "",     // a link to click on story
            linkText: "", // link text
            time: "",     // optional a date to display with the story item. unix timestamp are converted to "time ago" format
            seen: false   // set true if current user was read,
            
          }
    ]
})

console.log(Stories);