class Story {
    constructor(story) {
      this.id = story.id,               // story id
      this.photo = story.photo,          // story photo (or user photo)
      this.name = story.name,             // story name (or user name)
      this.link = story.link,             // story link (useless on story generated by script)
      this.lastUpdated = story.lastUpdated,      // last updated date in unix time format
      this.seen = false,          // set true if user has opened
      this.parentElId = story.parentElId

      this.items = story.items
    //   [              // array of items
    //       // story item example
    //       {
    //         id: "",       // item id
    //         type: "",     // photo or video
    //         length: 3,    // photo timeout or video length in seconds - uses 3 seconds timeout for images if not set
    //         src: "",      // photo or video src
    //         preview: "",  // optional - item thumbnail to show in the story carousel instead of the story defined image
    //         link: "",     // a link to click on story
    //         linkText: "", // link text
    //         time: "",     // optional a date to display with the story item. unix timestamp are converted to "time ago" format
    //         seen: false   // set true if current user was read,
            
    //       }
    //     ]
      
    }

    // methods will be written below

    // build a story
    createStory(){
      console.log("creating a story in => #", this.parentElId);
      const childDiv = document.createElement("div");
      childDiv.id = "conic-gradient"
      
      // creating an img tag for our display image, e.g user profile picture
      const displayImg = document.createElement("img"); 
      displayImg.src = this.photo; // setting the photo passed in as props to your src image element creared

      // mouseover event listener on the image
      displayImg.addEventListener('mouseover', function() {
        // console.log('Event mouseover triggered',displayImg);
        displayImg.style.transition = ".5s";
        displayImg.style.width = "78px";
      });

      // mouseout event listener on the image
       displayImg.addEventListener('mouseout', function() {
        // console.log('Event mouseout triggered',displayImg);
        displayImg.style.transition = ".7s";
        displayImg.style.width = "75px";
      });

      document.getElementById(this.parentElId).appendChild(childDiv)
      document.getElementById(childDiv.id).appendChild(displayImg);


      this.createStoryLine();

    }

    // creat the storyline
    createStoryLine(){
     let loading = document.getElementById("loading");
      this.items.map((item)=>{
        // console.log(item);
        // creating a storyBar
        const storyBar = document.createElement("div");
        storyBar.classList.add("story-bar");

        // only set progress bar if seen is true
          // creating a checking loader
          const checking = document.createElement("div");
          checking.classList.add("checker");
          storyBar.appendChild(checking);
        

        //appending the storyBar divs to the loading div
        loading.appendChild(storyBar); 

      });

      this.storyViewer();
    }

    // viewer function for viewing the story
    storyViewer(){
      let __self = this; // assigning global to self for later use
      let checker = document.getElementsByClassName("checker");
      // checker.classList.add("checking")
      //   __self.moveProgressBar(this.items[0].length);

      var counter = 0;  // the index of the current item to show

     const viewingBar = setInterval(function(){
        console.log("Hello");
        checker[counter].classList.add("checking");
        console.log(checker[counter++]);    // get the item and increment

        // clear if you've reached the end
        if(counter == checker.length){
          clearInterval(viewingBar);
        }
      },3000);

      

      // this.items.map((item, i) => {
      //   console.log(item);
      //   this.moveProgressBar(item.length);

      // });
        
        



    }

   
     moveProgressBar(length) {
      console.log(length)
    // loading bars
     var i = 0;
       if (i == 0) {
         i = 1;
         var elem = document.getElementsByClassName("checking")[0];
         var width = 1;
         var id = setInterval(frame, length);
         function frame() {
           if (width >= 100) {
             clearInterval(id);
             i = 0;
             console.log("fully loader")
           } else {
             width++;
             elem.style.width = width + "%";
           }
         }
       }
     }

  }